/* 当场战斗的增益、符文与规则触发器。由 battle.runtime.js 转发活绑定。 */
export let stealthStrike = false;
export let nextSpellTwice = 0;
export let spellCost1 = false;
export let meleeCost1 = false;
export let shaTransform = null;
export let consumeFireballN = 0;
export let lastPlayedType = null;
export let playedMartialThisTurn = 0;
export let playedMovesThisTurn = 0;
export let growthNames = new Set();
export let growth = {};
export let infuseFuels = 0;
export let sealUnlocked = false;
export let extraTurn = false;
export let deathSave = 0;
export let killAtkUp = 0;
export let poisonOnSpell = false;
export let poisonLegacy = false;
export let nestRunes = [];
export let nestSyn = {};
export let timeRune = false;
export let arrowRune = false;
export let unyieldRune = false;
export let ashRune = false;
export let unlimitedRune = false;
export let holyRune = false;
export let fireballRuneOn = false;
export let freezeRuneOn = false;
export let swiftRune = false;
export let timeSpaceRune = false;
export let timeSpaceUsed = false;
export let armorMul = 1;
export let sealDone = false;
export let playerCurseImmune = false;
export let allSpellsInfused = false;

export function set$stealthStrike(v) { stealthStrike = v; }
export function set$nextSpellTwice(v) { nextSpellTwice = v; }
export function set$spellCost1(v) { spellCost1 = v; }
export function set$meleeCost1(v) { meleeCost1 = v; }
export function set$shaTransform(v) { shaTransform = v; }
export function set$consumeFireballN(v) { consumeFireballN = v; }
export function set$lastPlayedType(v) { lastPlayedType = v; }
export function set$playedMartialThisTurn(v) { playedMartialThisTurn = v; }
export function set$playedMovesThisTurn(v) { playedMovesThisTurn = v; }
export function set$growthNames(v) { growthNames = v; }
export function set$growth(v) { growth = v; }
export function set$infuseFuels(v) { infuseFuels = v; }
export function set$sealUnlocked(v) { sealUnlocked = v; }
export function set$extraTurn(v) { extraTurn = v; }
export function set$deathSave(v) { deathSave = v; }
export function set$killAtkUp(v) { killAtkUp = v; }
export function set$poisonOnSpell(v) { poisonOnSpell = v; }
export function set$poisonLegacy(v) { poisonLegacy = v; }
export function set$nestRunes(v) { nestRunes = v; }
export function set$nestSyn(v) { nestSyn = v; }
export function set$timeRune(v) { timeRune = v; }
export function set$arrowRune(v) { arrowRune = v; }
export function set$unyieldRune(v) { unyieldRune = v; }
export function set$ashRune(v) { ashRune = v; }
export function set$unlimitedRune(v) { unlimitedRune = v; }
export function set$holyRune(v) { holyRune = v; }
export function set$fireballRuneOn(v) { fireballRuneOn = v; }
export function set$freezeRuneOn(v) { freezeRuneOn = v; }
export function set$swiftRune(v) { swiftRune = v; }
export function set$timeSpaceRune(v) { timeSpaceRune = v; }
export function set$timeSpaceUsed(v) { timeSpaceUsed = v; }
export function set$armorMul(v) { armorMul = v; }
export function set$sealDone(v) { sealDone = v; }
export function set$playerCurseImmune(v) { playerCurseImmune = v; }
export function set$allSpellsInfused(v) { allSpellsInfused = v; }
