// ESLint flat config（2026-09-23 基线）。
// 说明：eslint@10 不再依赖 @eslint/js 与 globals 包，为不加新依赖：
//   - recommended 规则集自上游 @eslint/js 的 eslint-recommended 配置原样内联（全 "error"）；
//   - 浏览器 / Node 全局与项目全局（window.SDT 等）手工声明，保证对现有代码零误报。
// 只做正确性检查，不开任何风格 / 格式类规则（stylistic 一律不上）。

const recommendedRules = {
  'constructor-super': 'error',
  'for-direction': 'error',
  'getter-return': 'error',
  'no-async-promise-executor': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-const-assign': 'error',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-empty-static-block': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-import-assign': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-self-assign': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-this-before-super': 'error',
  'no-unassigned-vars': 'error',
  'no-undef': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-labels': 'error',
  'no-unused-private-class-members': 'error',
  'no-unused-vars': 'error',
  'no-useless-assignment': 'error',
  'no-useless-backreference': 'error',
  'no-useless-catch': 'error',
  'no-useless-escape': 'error',
  'no-with': 'error',
  'preserve-caught-error': 'error',
  'require-yield': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
};

// 等效于 globals 包的 browser 集合（项目实际触达的 + 常见 DOM 接口全量声明）。
const browserGlobals = {
  window: 'readonly',
  self: 'readonly',
  document: 'readonly',
  console: 'readonly',
  // 定时器与调度
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  reportError: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  fetch: 'readonly',
  // window 上的事件与尺寸 API（允许裸调用）
  addEventListener: 'readonly',
  removeEventListener: 'readonly',
  dispatchEvent: 'readonly',
  innerWidth: 'readonly',
  innerHeight: 'readonly',
  outerWidth: 'readonly',
  outerHeight: 'readonly',
  devicePixelRatio: 'readonly',
  scrollX: 'readonly',
  scrollY: 'readonly',
  scrollTo: 'readonly',
  scrollBy: 'readonly',
  matchMedia: 'readonly',
  getComputedStyle: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  open: 'readonly',
  close: 'readonly',
  focus: 'readonly',
  blur: 'readonly',
  print: 'readonly',
  postMessage: 'readonly',
  history: 'readonly',
  location: 'readonly',
  navigator: 'readonly',
  performance: 'readonly',
  screen: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  crypto: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  Headers: 'readonly',
  AbortController: 'readonly',
  WebSocket: 'readonly',
  Worker: 'readonly',
  Image: 'readonly',
  Audio: 'readonly',
  Option: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  ErrorEvent: 'readonly',
  PromiseRejectionEvent: 'readonly',
  MessageEvent: 'readonly',
  KeyboardEvent: 'readonly',
  MouseEvent: 'readonly',
  PointerEvent: 'readonly',
  TouchEvent: 'readonly',
  WheelEvent: 'readonly',
  InputEvent: 'readonly',
  FocusEvent: 'readonly',
  DragEvent: 'readonly',
  UIEvent: 'readonly',
  EventTarget: 'readonly',
  Node: 'readonly',
  NodeFilter: 'readonly',
  Element: 'readonly',
  HTMLElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  HTMLImageElement: 'readonly',
  HTMLVideoElement: 'readonly',
  HTMLAudioElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLIFrameElement: 'readonly',
  HTMLAnchorElement: 'readonly',
  HTMLDivElement: 'readonly',
  HTMLSpanElement: 'readonly',
  SVGElement: 'readonly',
  SVGSVGElement: 'readonly',
  CanvasRenderingContext2D: 'readonly',
  CanvasGradient: 'readonly',
  CanvasPattern: 'readonly',
  ImageBitmap: 'readonly',
  OffscreenCanvas: 'readonly',
  DOMParser: 'readonly',
  XMLSerializer: 'readonly',
  DOMRect: 'readonly',
  DOMRectReadOnly: 'readonly',
  DOMException: 'readonly',
  Path2D: 'readonly',
  createImageBitmap: 'readonly',
  Storage: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  MutationObserver: 'readonly',
  PerformanceObserver: 'readonly',
  MediaQueryList: 'readonly',
  CSS: 'readonly',
  StyleMedia: 'readonly',
  AudioContext: 'readonly',
  webkitAudioContext: 'readonly',
  OfflineAudioContext: 'readonly',
  AudioBuffer: 'readonly',
  AudioNode: 'readonly',
  GainNode: 'readonly',
  OscillatorNode: 'readonly',
  AnalyserNode: 'readonly',
  BiquadFilterNode: 'readonly',
  MediaElementAudioSourceNode: 'readonly',
  MediaRecorder: 'readonly',
  speechSynthesis: 'readonly',
  SpeechSynthesisUtterance: 'readonly',
  visualViewport: 'readonly',
  caches: 'readonly',
  ServiceWorker: 'readonly',
  indexedDB: 'readonly',
  IDBDatabase: 'readonly',
  IDBTransaction: 'readonly',
  IDBObjectStore: 'readonly',
  IDBRequest: 'readonly',
  IDBKeyRange: 'readonly',
};

// 测试 / 工具代码触达的 Node 全局（vitest 运行环境可用）。
const nodeGlobals = {
  process: 'readonly',
  global: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  require: 'readonly',
  module: 'writable',
  exports: 'writable',
};

// 项目全局：window.SDT 挂载点与 vite define 注入的构建期常量。
// 代码里普遍用 `const SDT = window.SDT` 局部接收，局部声明会正确遮蔽此全局。
const projectGlobals = {
  SDT: 'readonly',
  sdtDesktop: 'readonly',
  __BUILD_VERSION__: 'readonly',
};

export default [
  {
    files: ['game/src/**/*.js', 'tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...browserGlobals,
        ...nodeGlobals,
        ...projectGlobals,
      },
    },
    rules: {
      ...recommendedRules,
    },
  },
];
