import { defineConfig } from 'vite';
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, rmSync, chmodSync } from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// 逐文件读写拷贝：copyFileSync 在 Windows 下对只读源文件会 EPERM，read+write 则正常
function copyDir(src, dest, relativePrefix = '') {
  mkdirSync(dest, { recursive: true });
  for (const e of readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name), d = path.join(dest, e.name);
    const relativeAsset = relativePrefix ? `${relativePrefix}/${e.name}` : e.name;
    if (e.isDirectory()) copyDir(s, d, relativeAsset);
    else {
      if (getAliasedDuplicateAssets().has(relativeAsset)) continue;
      // 只读残留会令 writeFileSync EPERM，且 rmSync 对只读文件静默失败，先清属性再删
      try { chmodSync(d, 0o666); } catch { /* 不存在则忽略 */ }
      rmSync(d, { force: true });
      writeFileSync(d, readFileSync(s));
    }
  }
}

function clearGeneratedDir(dir) {
  const expectedParent = path.join(ROOT, 'desktop-app');
  const relative = path.relative(expectedParent, dir);
  if (!relative || relative.startsWith('..') || path.isAbsolute(relative) || !path.basename(dir).startsWith('game')) {
    throw new Error(`Refusing to clear unexpected build directory: ${dir}`);
  }
  if (!existsSync(dir)) return;
  // node 的 rmSync 在部分环境下会静默失败（不删除也不报错），旧哈希产物因此逐次堆积；
  // 改用系统原生命令删除，删除后必须校验目录确实消失，失败则大声警告并给出手动命令
  const nativeRemove = process.platform === 'win32'
    ? `rd /s /q "${dir}"`
    : `rm -rf "${dir}"`;
  try { execSync(nativeRemove, { stdio: 'ignore' }); } catch { /* 由下方 existsSync 兜底校验 */ }
  if (existsSync(dir)) {
    console.warn('[assets] WARNING: 旧产物目录删除失败，本次构建将与旧产物混叠！');
    console.warn(`[assets] 请先手动执行删除再构建: ${nativeRemove}`);
  } else {
    console.log(`[assets] cleared generated directory: ${dir}`);
  }
}

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const GAME_ROOT = path.join(ROOT, 'game');
const OUT_DIR = process.env.SDT_BUILD_OUT_DIR
  ? path.resolve(ROOT, process.env.SDT_BUILD_OUT_DIR)
  : path.join(ROOT, 'desktop-app', 'game');
const RUNTIME_ASSET_DIRS = ['cards', 'portraits', 'icons', 'scenes', 'thumbs', path.join('ui', 'icons'), 'sfx'];
const ASSETS_ROOT = path.join(GAME_ROOT, 'assets');
const RUNTIME_ASSET_PREFIXES = RUNTIME_ASSET_DIRS.map(dir => dir.split(path.sep).join('/') + '/');
// 美术清单扫描范围：RUNTIME 目录去掉 sfx（音频不是美术）与 thumbs（缩略图按需取用；
// 进清单会被全量预热，等于原图+缩略图两份位图都常驻，与预加载初衷相反）。图片扩展名兜底过滤。
const ART_MANIFEST_DIRS = RUNTIME_ASSET_DIRS.filter(dir => dir !== 'sfx' && dir !== 'thumbs');
const IMAGE_EXT_RE = /\.(webp|png|jpe?g|gif|svg)$/i;
const ITEM_ART_ALIAS = Object.freeze({ id: 'tt-token-color', target: 'cmtmvq6ss84l' });
let aliasedDuplicateAssets = null;

// 仅当权威 itemArt 仍指向等字节别名时，从发布清单与副本中省略旧键文件。
// 若映射被恢复为独立素材，或两份源文件发生分歧，则自动保留两份。
function getAliasedDuplicateAssets() {
  if (aliasedDuplicateAssets) return aliasedDuplicateAssets;
  aliasedDuplicateAssets = new Set();
  const mapping = JSON.parse(readFileSync(path.join(GAME_ROOT, 'data', 'art-mapping.json'), 'utf8'));
  if (mapping.itemArt?.[ITEM_ART_ALIAS.id] !== ITEM_ART_ALIAS.target) return aliasedDuplicateAssets;
  for (const prefix of ['cards/items', 'thumbs/cards/items']) {
    const oldAsset = `${prefix}/${ITEM_ART_ALIAS.id}.webp`;
    const targetAsset = `${prefix}/${ITEM_ART_ALIAS.target}.webp`;
    const oldPath = path.join(ASSETS_ROOT, ...oldAsset.split('/'));
    const targetPath = path.join(ASSETS_ROOT, ...targetAsset.split('/'));
    if (existsSync(oldPath) && existsSync(targetPath)
      && readFileSync(oldPath).equals(readFileSync(targetPath))) aliasedDuplicateAssets.add(oldAsset);
  }
  return aliasedDuplicateAssets;
}

// 递归收集目录下图片文件，返回相对 assets/ 的 POSIX 路径
function collectImageFiles(dir, prefix = '') {
  if (!existsSync(dir)) return [];
  const found = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${e.name}` : e.name;
    if (e.isDirectory()) found.push(...collectImageFiles(path.join(dir, e.name), rel));
    else if (IMAGE_EXT_RE.test(e.name)) found.push(rel);
  }
  return found;
}

// 全量美术预加载清单（2026-09-13 老板：游戏内所有美术资源改成预加载）：
// 构建期扫描生成 game/src/generated/art-manifest.js，art.js 按它补热。
// 新增/删除图片后重跑构建清单自动更新，运行时零维护。
function writeArtManifest() {
  const omittedAliases = getAliasedDuplicateAssets();
  const files = ART_MANIFEST_DIRS.flatMap(dir => collectImageFiles(path.join(GAME_ROOT, 'assets', dir), dir))
    .filter(file => !omittedAliases.has(file));
  const target = path.join(GAME_ROOT, 'src', 'generated', 'art-manifest.js');
  writeFileSync(
    target,
    `// AUTO-GENERATED by vite.config.js (writeArtManifest) — 每次构建重新生成，勿手改。\n`
    + `// 全量美术预加载清单：assets/ 下 RUNTIME 资产目录的全部图片（POSIX 相对路径）。\n`
    + `export default ${JSON.stringify(files, null, 2)};\n`,
  );
  console.log(`[assets] art manifest: ${files.length} images -> ${path.relative(ROOT, target)}`);
}

// 卡面缩略图清单（assets/thumbs/**，由 game/tools/bake-card-thumbs.cjs 烘焙）：
// art.js 靠它判断某张图有没有缩略图变体，没有就回退原图，不会打 404。
// 这里重写一份是为了新增/删除缩略图后无需手动同步；thumbs 目录不存在时写出空清单。
function writeThumbManifest() {
  const omittedAliases = getAliasedDuplicateAssets();
  const files = collectImageFiles(path.join(GAME_ROOT, 'assets', 'thumbs'))
    .filter(file => !omittedAliases.has(`thumbs/${file}`)).sort();
  const target = path.join(GAME_ROOT, 'src', 'generated', 'thumb-manifest.js');
  writeFileSync(
    target,
    `// AUTO-GENERATED by vite.config.js (writeThumbManifest) / game/tools/bake-card-thumbs.cjs — 勿手改。\n`
    + `// 卡面缩略图清单：assets/thumbs/ 下全部图片（相对 thumbs/ 的 POSIX 路径）。\n`
    + `export default ${JSON.stringify(files, null, 2)};\n`,
  );
  console.log(`[assets] thumb manifest: ${files.length} images -> ${path.relative(ROOT, target)}`);
}

// 构建版本号（迭代评审 09-20 D-P2）：只取 version.json 的版本号，不再拼 Date.now()——
// 时间戳会让每次构建的全部资产 URL 变更，频繁构建下等效全量缓存失效；
// 版本随发版推进即失效，查询参数由 copyStatic.closeBundle 的产物级重写统一补齐
function buildVersion() {
  try {
    const { version } = JSON.parse(readFileSync(path.join(GAME_ROOT, 'version.json'), 'utf8'));
    return `${version}`;
  } catch {
    return 'dev';
  }
}

// 静态引用与动态 assetUrl 引用统一落到同一份稳定路径。
// 过去静态引用输出 hash 文件、copyStatic 又复制原文件，单次构建会白白多出约 10MB。
function assetFileName(assetInfo) {
  const originals = assetInfo.originalFileNames || [];
  for (const original of originals) {
    // Vite/Rollup 报告的是相对 root(game/) 的路径，不是相对仓库根目录。
    const absolute = path.isAbsolute(original) ? original : path.resolve(GAME_ROOT, original);
    const relative = path.relative(ASSETS_ROOT, absolute).split(path.sep).join('/');
    if (relative.startsWith('../') || path.isAbsolute(relative)) continue;
    if (RUNTIME_ASSET_PREFIXES.some(prefix => relative.startsWith(prefix))) return `assets/${relative}`;
  }
  return 'assets/[name]-[hash][extname]';
}

// 只复制无法由 Vite 静态分析的动态资源族；其余图片、场景和音乐交给
// new URL(..., import.meta.url) / CSS 管线哈希，避免产物同时保留哈希版和原始版。
function copyStatic() {
  return {
    name: 'copy-static',
    apply: 'build',
    buildStart() {
      clearGeneratedDir(OUT_DIR);
      console.log(`[assets] cleared generated directory: ${OUT_DIR}`);
      // 模块解析前重写清单，保证本次构建的新增/删除图片立即生效
      writeArtManifest();
      writeThumbManifest();
    },
    closeBundle() {
      const srcAssets = path.join(GAME_ROOT, 'assets');
      for (const relativeDir of RUNTIME_ASSET_DIRS) {
        const source = path.join(srcAssets, relativeDir);
        if (existsSync(source)) copyDir(source, path.join(OUT_DIR, 'assets', relativeDir), relativeDir.split(path.sep).join('/'));
      }
      writeFileSync(path.join(OUT_DIR, 'version.json'), readFileSync(path.join(GAME_ROOT, 'version.json')));
      patchAssetVersions();
      // 哨兵：正常构建产出 1 个入口 + 1 个异步 index chunk（共 2 个）；更多说明旧产物未清掉
      const jsDir = path.join(OUT_DIR, 'assets', 'js');
      if (existsSync(jsDir)) {
        const entries = readdirSync(jsDir).filter(name => /^index-.*\.js$/.test(name));
        if (entries.length > 2) {
          console.warn(`[assets] WARNING: 产物中出现 ${entries.length} 个 index bundle（应为 2 个），旧产物未清理干净: ${entries.join(', ')}`);
        }
      }
    },
  };
}

// 产物级静态资产缓存失效（迭代评审 09-20 D-P1/P2）：构建完成后重写 OUT_DIR 内的 JS/CSS，
// 给静态资产引用统一补 ?v=<version.json 版本>。只命中两种模式（引擎岗 R2 终裁口径）——
//   ① JS 内 new URL("assets/…") 字面量（Vite 打包后的静态引用）
//   ② CSS 内 url(…assets/…)
// 其余字符串（含运行时经 assetUrl() 自拼 ?v= 的 RUNTIME 路径）一律不碰，避免双版本参数；
// 版本号取 version.json（无时间戳），随发版推进即失效，频繁构建不产生缓存抖动。
function patchAssetVersions() {
  const version = buildVersion();
  const JS_RE = /new URL\((['"])(\.\/)?(assets\/[^'"]+?\.(?:webp|png|jpe?g|gif|svg|mp3|ogg|wav))\1/g;
  const CSS_RE = /url\((['"]?)([^)'"]*?assets\/[^)'"]+?\.(?:webp|png|jpe?g|gif|svg|mp3|ogg|wav|woff2?|ttf))\1\)/g;
  const walk = (dir) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) { walk(full); continue; }
      if (!/\.(js|css)$/.test(e.name)) continue;
      const isCss = e.name.endsWith('.css');
      const before = readFileSync(full, 'utf8');
      const after = isCss
        ? before.replace(CSS_RE, (m, q, p) => p.includes('?v=') ? m : `url(${q}${p}?v=${version}${q})`)
        : before.replace(JS_RE, (m, q, dot, p) => p.includes('?v=') ? m : `new URL(${q}${dot || ''}${p}?v=${version}${q}`);
      if (after !== before) { writeFileSync(full, after); }
    }
  };
  walk(OUT_DIR);
  console.log(`[assets] asset URLs versioned: ?v=${version}`);
}

export default defineConfig({
  root: GAME_ROOT,
  base: './',
  publicDir: false,
  define: {
    __BUILD_VERSION__: JSON.stringify(buildVersion()),
  },
  test: {
    root: ROOT,
    environment: 'jsdom',
    include: ['tests/**/*.test.js'],
  },
  build: {
    outDir: OUT_DIR,
    emptyOutDir: true,
    // 音频/图片一律出文件，不内联 base64（桌面端 file 协议下更稳，也便于缓存）
    assetsInlineLimit: 0,
    rollupOptions: {
      output: {
        entryFileNames: 'assets/js/[name]-[hash].js',
        chunkFileNames: 'assets/js/[name]-[hash].js',
        assetFileNames: assetFileName,
        // 大依赖各自成 chunk：主入口回到 500kB 以下，且库不升级时哈希稳定利于缓存。
        // three 分支删除（迭代评审 09-20 D-P3）：three 为死依赖已移除，规则永不命中徒增误导
        manualChunks(id) {
          const normalized = id.split(path.sep).join('/');
          // 卡牌定义与目录解析是稳定内容数据层：独立缓存，但仍是静态启动依赖，
          // perf-budget 的首屏总量会继续完整计入该 chunk。
          if (/\/game\/src\/(?:cards\.(?:data|catalog|consts)|data-loader)\.js$/.test(normalized)) return 'game-card-catalog';
          if (/[\\/]node_modules[\\/](pixi\.js|@pixi)[\\/]/.test(id)) return 'vendor-render';
          if (/[\\/]node_modules[\\/]inkjs[\\/]/.test(id)) return 'vendor-narrative';
          if (/[\\/]node_modules[\\/](howler|motion)[\\/]/.test(id)) return 'vendor-runtime';
        },
      },
    },
  },
  plugins: [copyStatic()],
});
