<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\Core\**\*.cs" />
    <Compile Remove="..\..\src\Core\Run\**\*.cs" />
    <Compile Include="CombatTests.cs" />
  </ItemGroup>
</Project>
