/* battle.runtime.js —— 战斗运行时状态容器（2026-09-22 六文件重构批6-A 自 battle.core.js 外置）。
 * 模块级 let 状态的唯一属地：battle.core 壳与各切片具名 import 读（活绑定）、set$Xxx(v) 写
 * （ESM 导入绑定不可赋值）。声明逐字搬迁、初值语义不变；setter 仅覆盖真实发生重绑的名字。 */
import { createBattleState } from './battle.state.js';

  export let renderBattle = () => {};
  export let battleState = createBattleState();
  export let G = null;
  export let foes = [];
  export let opts = null;
  export let mode = 'normal';
  export let drawPile = [], hand = [], discard = [], granted = [];
  export let played = [], consumed = [];
  export let grave = [];
  export let energy = 0, maxEnergy = 0, turn = 1;
  export let pdef = null, pstat = null;
  export let busy = false;
  export let infusing = null, discovering = null, discoverQueue = [];
  export let handSelecting = null;
  export let choosing = null;
  export let stealthStrike = false;
  export let nextSpellTwice = 0;
  export let interaction = null;
  export let pendingHint = '';
  export let delayed = [];
  export let noDrawNext = false;
  export let viewingGrave = false;
  export let viewingDeck = false;
  export let viewingBag = false;
  export let floats = [];
  export let cardAnims = [];
  export let presentationActionSeq = 0;
  export let dreadShown = false;
  export let spellCost1 = false;
  export let meleeCost1 = false;
  export let shaTransform = null;
  export let consumeFireballN = 0;
  export let lastDrawnUids = [];
  export let lastPlayedType = null;
  export let playedMartialThisTurn = 0;
  export let playedMovesThisTurn = 0;
  export let selPool = [], selShaN = 0, sel = new Set(), lastDeckSel = [], selectingDeck = false, selDeckMax = 15;
  export let allies = [];
  export let growthNames = new Set();
  export let growth = {};
  export let infuseFuels = 0;
  export let sealUnlocked = false;
  export let extraTurn = false;
  export let deathSave = 0;
  export let killAtkUp = 0;
  export let poisonOnSpell = false;
  export let poisonLegacy = false;
  export let nestRunes = [];
  export let nestSyn = {};
  export let timeRune = false;
  export let arrowRune = false;
  export let unyieldRune = false;
  export let ashRune = false;
  export let unlimitedRune = false;
  export let holyRune = false;
  export let fireballRuneOn = false;
  export let freezeRuneOn = false;
  export let swiftRune = false;
  export let timeSpaceRune = false;
  export let timeSpaceUsed = false;
  export let armorMul = 1;
  export let sealDone = false;
  export let playerCurseImmune = false;
  export let allSpellsInfused = false;
  export let zeroFeeUntil = new Map();
  export let cardOverrides = new Map();
  export let equipped = [];
  export let freeCast = new Set();
  export let battleRestartCheckpoint = null;
  export let restoringRestartCheckpoint = false;
  export let tmpSeq = 0;
  export let activeActionSignal = null;
  export let surgeWaiter = null;
  export let lastPersistAt = 0;
  export let snapCache = null, snapSig = null;

export function set$renderBattle(v) { renderBattle = v; }
export function set$lastDrawnUids(v) { lastDrawnUids = v; }
export function set$tmpSeq(v) { tmpSeq = v; }
export function set$noDrawNext(v) { noDrawNext = v; }
export function set$stealthStrike(v) { stealthStrike = v; }
export function set$nextSpellTwice(v) { nextSpellTwice = v; }
export function set$drawPile(v) { drawPile = v; }
export function set$energy(v) { energy = v; }
export function set$maxEnergy(v) { maxEnergy = v; }
export function set$shaTransform(v) { shaTransform = v; }
export function set$consumeFireballN(v) { consumeFireballN = v; }
export function set$deathSave(v) { deathSave = v; }
export function set$hand(v) { hand = v; }
export function set$extraTurn(v) { extraTurn = v; }
export function set$delayed(v) { delayed = v; }
export function set$meleeCost1(v) { meleeCost1 = v; }
export function set$spellCost1(v) { spellCost1 = v; }
export function set$surgeWaiter(v) { surgeWaiter = v; }
export function set$sealUnlocked(v) { sealUnlocked = v; }
export function set$discovering(v) { discovering = v; }
export function set$G(v) { G = v; }
export function set$battleRestartCheckpoint(v) { battleRestartCheckpoint = v; }
export function set$opts(v) { opts = v; }
export function set$mode(v) { mode = v; }
export function set$battleState(v) { battleState = v; }
export function set$foes(v) { foes = v; }
export function set$interaction(v) { interaction = v; }
export function set$selPool(v) { selPool = v; }
export function set$selShaN(v) { selShaN = v; }
export function set$sel(v) { sel = v; }
export function set$discard(v) { discard = v; }
export function set$granted(v) { granted = v; }
export function set$played(v) { played = v; }
export function set$consumed(v) { consumed = v; }
export function set$grave(v) { grave = v; }
export function set$turn(v) { turn = v; }
export function set$busy(v) { busy = v; }
export function set$pdef(v) { pdef = v; }
export function set$pstat(v) { pstat = v; }
export function set$infusing(v) { infusing = v; }
export function set$discoverQueue(v) { discoverQueue = v; }
export function set$handSelecting(v) { handSelecting = v; }
export function set$floats(v) { floats = v; }
export function set$cardAnims(v) { cardAnims = v; }
export function set$presentationActionSeq(v) { presentationActionSeq = v; }
export function set$choosing(v) { choosing = v; }
export function set$lastPlayedType(v) { lastPlayedType = v; }
export function set$viewingGrave(v) { viewingGrave = v; }
export function set$viewingDeck(v) { viewingDeck = v; }
export function set$dreadShown(v) { dreadShown = v; }
export function set$selectingDeck(v) { selectingDeck = v; }
export function set$viewingBag(v) { viewingBag = v; }
export function set$allies(v) { allies = v; }
export function set$growthNames(v) { growthNames = v; }
export function set$growth(v) { growth = v; }
export function set$infuseFuels(v) { infuseFuels = v; }
export function set$killAtkUp(v) { killAtkUp = v; }
export function set$poisonOnSpell(v) { poisonOnSpell = v; }
export function set$poisonLegacy(v) { poisonLegacy = v; }
export function set$zeroFeeUntil(v) { zeroFeeUntil = v; }
export function set$cardOverrides(v) { cardOverrides = v; }
export function set$sealDone(v) { sealDone = v; }
export function set$playerCurseImmune(v) { playerCurseImmune = v; }
export function set$allSpellsInfused(v) { allSpellsInfused = v; }
export function set$nestRunes(v) { nestRunes = v; }
export function set$nestSyn(v) { nestSyn = v; }
export function set$timeRune(v) { timeRune = v; }
export function set$arrowRune(v) { arrowRune = v; }
export function set$unyieldRune(v) { unyieldRune = v; }
export function set$ashRune(v) { ashRune = v; }
export function set$unlimitedRune(v) { unlimitedRune = v; }
export function set$holyRune(v) { holyRune = v; }
export function set$fireballRuneOn(v) { fireballRuneOn = v; }
export function set$freezeRuneOn(v) { freezeRuneOn = v; }
export function set$swiftRune(v) { swiftRune = v; }
export function set$timeSpaceRune(v) { timeSpaceRune = v; }
export function set$timeSpaceUsed(v) { timeSpaceUsed = v; }
export function set$armorMul(v) { armorMul = v; }
export function set$freeCast(v) { freeCast = v; }
export function set$equipped(v) { equipped = v; }
export function set$playedMartialThisTurn(v) { playedMartialThisTurn = v; }
export function set$playedMovesThisTurn(v) { playedMovesThisTurn = v; }
export function set$selDeckMax(v) { selDeckMax = v; }
export function set$lastDeckSel(v) { lastDeckSel = v; }
export function set$pendingHint(v) { pendingHint = v; }
export function set$lastPersistAt(v) { lastPersistAt = v; }
export function set$activeActionSignal(v) { activeActionSignal = v; }
export function set$restoringRestartCheckpoint(v) { restoringRestartCheckpoint = v; }
export function set$snapSig(v) { snapSig = v; }
export function set$snapCache(v) { snapCache = v; }
